// dotenv
require("dotenv").config({ quiet: true });

// express
const express = require("express");
const app = express();
app.set("trust proxy", 1);

app.use(express.urlencoded({ extended: true }));
app.use(express.json());

// Router
const watchRouter = require("./Routes/watch");
const reviewRouter = require("./routes/review");
const userRouter = require("./routes/auth");
const cartRouter = require("./routes/cart");

// Extra
const createError = require("http-errors");

// Mongoose
const mongoose = require("mongoose");

const main = async () => {
  try {
    await mongoose.connect(process.env.DATABASE_URL_Local);
    console.log("DataBase Connected Successfully");
    app.listen(process.env.PORT || 8080, () => {
      console.log("Server Started Successfully");
    });
  } catch (err) {
    console.log(err);
  }
};

// Cors and Cookie Parser
const cors = require("cors");
const cookieParser = require("cookie-parser");

const allowedOrigins = [
  "http://localhost:5173",
  // "https://book-shelf-two-peach.vercel.app",
  // "https://book-shelf-git-main-ninjaz9s-projects.vercel.app",
];

// 2. Create a smart CORS function
const corsOptions = {
  origin: function (origin, callback) {
    // Allow requests with no origin (like Postman or mobile apps)
    if (!origin) return callback(null, true);

    // Check if the URL is in our exact list above
    if (allowedOrigins.includes(origin)) {
      return callback(null, true);
    }
    // MAGIC TRICK: Automatically allow any dynamic Vercel deployment URL generated by your account
    else if (origin.endsWith("-ninjaz9s-projects.vercel.app")) {
      return callback(null, true);
    }
    // Block everything else
    else {
      return callback(new Error("Blocked by CORS policy"), false);
    }
  },
  methods: "GET,PUT,PATCH,POST,DELETE",
  credentials: true,
  optionsSuccessStatus: 200,
};

app.use(cors(corsOptions));
app.use(cookieParser());

// Starting Routes
app.get("/", (req, res) => {
  res.send(`<h1>Your Watch Website is working <a href="/api/watch">Here</a><h1>`);
});

// main routes
app.use("/api/watch", watchRouter);

app.use("/api/watch/:id/reviews", reviewRouter);

app.use("/api", userRouter);

app.use("/api/cart", cartRouter);

// Error Routes
app.use((req, res, next) => {
  return next(createError(404, "Page Not Found"));
});

app.use((err, req, res, next) => {
  const { status = 404, message = "Error Please Try Again Later" } = err;
  res.status(status).json({ msg: message });
});

main();
